import Homey from 'homey';
import PairSession from 'homey/lib/PairSession';
import { randomUUID } from 'crypto';
import { registerVirtualFlowCards } from './flow';
import { VirtualFlowConfig } from './types';

/**
 * Shared behavior for all virtual drivers:
 * - registers the driver's flow card run listeners from a declarative config,
 * - implements pairing through the shared custom view (pair/start.html,
 *   generated by scripts/sync-pairing.js): the user picks a name and an
 *   icon, after which the view calls Homey.createDevice() itself. The
 *   backend only hands out a localized default name and a unique id.
 */
export default abstract class BaseVirtualDriver extends Homey.Driver {
  protected abstract readonly flowConfig: VirtualFlowConfig;

  async onInit(): Promise<void> {
    registerVirtualFlowCards(this.homey, this.flowConfig);
    this.log(`${this.constructor.name} initialized`);
  }

  async onPair(session: PairSession): Promise<void> {
    session.setHandler('getPairInfo', async () => ({
      name: this.localizedDriverName(),
      id: randomUUID(),
    }));
  }

  /** Driver name from the manifest in the user's language, en as fallback. */
  private localizedDriverName(): string {
    const names = (this.manifest as { name?: Record<string, string> }).name ?? {};
    const language = this.homey.i18n.getLanguage();
    return names[language] ?? names.en ?? 'Virtual device';
  }
}
