#!/usr/bin/env node
/**
 * Syncs the shared pairing assets into every driver:
 * - copies assets/device-icons/*.svg to drivers/<id>/assets/icons/
 * - generates drivers/<id>/pair/start.html from pairing/start.template.html,
 *   inlining the icon grid and the driver's default icon.
 *
 * Single source of truth: assets/device-icons/ and pairing/start.template.html.
 * Run after changing either: npm run sync:pairing
 */
'use strict';

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const iconsDir = path.join(root, 'assets/device-icons');
const templateFile = path.join(root, 'pairing/start.template.html');

/** Driver id → default icon (must exist in assets/device-icons/). */
const DRIVERS = {
  'virtual-boolean': 'switch',
  'virtual-button': 'button',
  'virtual-number': 'number',
  'virtual-string': 'text',
  'virtual-temperature': 'temperature',
  'virtual-power': 'power',
  'virtual-battery': 'battery',
  'virtual-humidity': 'humidity',
  'virtual-luminance': 'luminance',
  'virtual-pressure': 'pressure',
  'virtual-co2': 'co2',
  'virtual-contact': 'contact',
  'virtual-motion': 'motion',
  'virtual-dimmer': 'dimmer',
  'virtual-energy': 'energy',
};

const iconFiles = fs
  .readdirSync(iconsDir)
  .filter((file) => file.endsWith('.svg'))
  .sort();
const iconNames = iconFiles.map((file) => path.basename(file, '.svg'));

function iconButton(name) {
  const svg = fs.readFileSync(path.join(iconsDir, `${name}.svg`), 'utf8').trim();
  return `<button type="button" class="vd-icon" data-icon="${name}" title="${name}">${svg}</button>`;
}

/** Grid with the driver's default icon first, the rest alphabetical. */
function buildGrid(defaultIcon) {
  const ordered = [defaultIcon, ...iconNames.filter((name) => name !== defaultIcon)];
  return ordered.map(iconButton).join('\n      ');
}

const template = fs.readFileSync(templateFile, 'utf8');

for (const [driver, defaultIcon] of Object.entries(DRIVERS)) {
  if (!iconNames.includes(defaultIcon)) {
    throw new Error(`Default icon '${defaultIcon}' for ${driver} not found in ${iconsDir}`);
  }
  const driverDir = path.join(root, 'drivers', driver);
  if (!fs.existsSync(driverDir)) {
    throw new Error(`Driver directory missing: ${driverDir}`);
  }

  const iconTarget = path.join(driverDir, 'assets/icons');
  fs.mkdirSync(iconTarget, { recursive: true });
  for (const file of iconFiles) {
    fs.copyFileSync(path.join(iconsDir, file), path.join(iconTarget, file));
  }

  const pairDir = path.join(driverDir, 'pair');
  fs.mkdirSync(pairDir, { recursive: true });
  const html = template
    .replace('__ICON_GRID__', buildGrid(defaultIcon))
    .replace('__DEFAULT_ICON__', defaultIcon)
    .replace(
      /^<!-- GENERATED SOURCE[\s\S]*?-->\n/m,
      '<!-- GENERATED by scripts/sync-pairing.js — do not edit; edit pairing/start.template.html -->\n',
    )
    .replace(/^<!-- Each drivers.*?-->\n/m, '');
  fs.writeFileSync(path.join(pairDir, 'start.html'), html);

  process.stdout.write(`synced ${driver} (default icon: ${defaultIcon})\n`);
}

process.stdout.write(`${iconFiles.length} icons × ${Object.keys(DRIVERS).length} drivers synced\n`);
